/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as UseTransitionPendingButtonImport } from './routes/useTransition/pendingButton'
import { Route as UseOptimisticCalculationImport } from './routes/useOptimistic/calculation'
import { Route as UseOptimisticAddToListImport } from './routes/useOptimistic/addToList'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UseTransitionPendingButtonRoute = UseTransitionPendingButtonImport.update(
  {
    id: '/useTransition/pendingButton',
    path: '/useTransition/pendingButton',
    getParentRoute: () => rootRoute,
  } as any,
)

const UseOptimisticCalculationRoute = UseOptimisticCalculationImport.update({
  id: '/useOptimistic/calculation',
  path: '/useOptimistic/calculation',
  getParentRoute: () => rootRoute,
} as any)

const UseOptimisticAddToListRoute = UseOptimisticAddToListImport.update({
  id: '/useOptimistic/addToList',
  path: '/useOptimistic/addToList',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/useOptimistic/addToList': {
      id: '/useOptimistic/addToList'
      path: '/useOptimistic/addToList'
      fullPath: '/useOptimistic/addToList'
      preLoaderRoute: typeof UseOptimisticAddToListImport
      parentRoute: typeof rootRoute
    }
    '/useOptimistic/calculation': {
      id: '/useOptimistic/calculation'
      path: '/useOptimistic/calculation'
      fullPath: '/useOptimistic/calculation'
      preLoaderRoute: typeof UseOptimisticCalculationImport
      parentRoute: typeof rootRoute
    }
    '/useTransition/pendingButton': {
      id: '/useTransition/pendingButton'
      path: '/useTransition/pendingButton'
      fullPath: '/useTransition/pendingButton'
      preLoaderRoute: typeof UseTransitionPendingButtonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useOptimistic/addToList': typeof UseOptimisticAddToListRoute
  '/useOptimistic/calculation': typeof UseOptimisticCalculationRoute
  '/useTransition/pendingButton': typeof UseTransitionPendingButtonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useOptimistic/addToList': typeof UseOptimisticAddToListRoute
  '/useOptimistic/calculation': typeof UseOptimisticCalculationRoute
  '/useTransition/pendingButton': typeof UseTransitionPendingButtonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useOptimistic/addToList': typeof UseOptimisticAddToListRoute
  '/useOptimistic/calculation': typeof UseOptimisticCalculationRoute
  '/useTransition/pendingButton': typeof UseTransitionPendingButtonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/useOptimistic/addToList'
    | '/useOptimistic/calculation'
    | '/useTransition/pendingButton'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/useOptimistic/addToList'
    | '/useOptimistic/calculation'
    | '/useTransition/pendingButton'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/useOptimistic/addToList'
    | '/useOptimistic/calculation'
    | '/useTransition/pendingButton'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UseOptimisticAddToListRoute: typeof UseOptimisticAddToListRoute
  UseOptimisticCalculationRoute: typeof UseOptimisticCalculationRoute
  UseTransitionPendingButtonRoute: typeof UseTransitionPendingButtonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UseOptimisticAddToListRoute: UseOptimisticAddToListRoute,
  UseOptimisticCalculationRoute: UseOptimisticCalculationRoute,
  UseTransitionPendingButtonRoute: UseTransitionPendingButtonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/useOptimistic/addToList",
        "/useOptimistic/calculation",
        "/useTransition/pendingButton"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/useOptimistic/addToList": {
      "filePath": "useOptimistic/addToList.tsx"
    },
    "/useOptimistic/calculation": {
      "filePath": "useOptimistic/calculation.tsx"
    },
    "/useTransition/pendingButton": {
      "filePath": "useTransition/pendingButton.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
